# Configuration for cnnspdnet on tengeop
# Model: cnnspdnet
# Dataset: tengeop

epochs: 200
lr: 0.00075
optimizer: adam
scheduler: plateau
scheduler_patience: 3
scheduler_factor: 0.3
scheduler_min_lr: 1.0e-05
early_stopping_patience: 10
storage_path: results/experiments
group_id: backbone_fusar
save_best_model: true
device: cuda
dtype: float64
seed: 42
verbose: true
preload: false
skip_label_check: true 
dataset_config:
  name: fusar
  path: ~/Documents/DATASET/FUSAR_Ship1.0
  train_ratio: 0.8
  val_ratio: 0.1
  batch_size: 48
  shuffle: true
  num_workers: 4
  resize_mode: fixed_size
  target_size: 
  - 224
  - 224
  max_samples: 200
  min_samples: 30
  channels: single
  class_level: basic
  drop: false
model_name: cnn
model_config:
  feature_channels:
  - 64
  - 96
  - 128
# NON EXISTENT PARAMETER IN CNN MODEL, ADDED FOR COMPATIBILITY
  hidden_layers_size:
  - 96
  - 48
  - 20
  shrinkage: none
  lbda: optimal
  eps: 0.5
  use_chunking: false
  chunk_size: null
  use_vech: false
  dropout_rate: 0.3