# Configuration for cnnspdnet on tengeop
# Model: cnnspdnet
# Dataset: tengeop

epochs: 200
lr: 0.00075
optimizer: adam
scheduler: plateau
scheduler_patience: 3
scheduler_factor: 0.3
scheduler_min_lr: 1.0e-05
early_stopping_patience: 10
storage_path: results/experiments
group_id: backbone_s1slc
save_best_model: true
device: cuda
dtype: float64
seed: 42
verbose: true
preload: false
skip_label_check: true 
dataset_config:
  name: s1slc
  path: ~/Documents/DATASET/S1SLC_CVDL/complex_HHHV.zarr
  train_ratio: 0.8
  val_ratio: 0.1
  batch_size: 48   
  shuffle: true
  num_workers: 4
  max_samples_per_class: 750
  channels: complex_dual
  mode: domain_adaptation
  train_cities:
  - Chicago
  - Houston
  test_city: Sao Paulo
model_name: cnn
model_config:
  feature_channels:
  - 48
  - 64
  hidden_layers_size:
  - 40
  - 14
  shrinkage: none
  lbda: optimal
  eps: 0.05
  use_chunking: false
  chunk_size: null
  use_vech: false
  dropout_rate: 0.3